### ISSUE TITLE
KitKat checklist

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#333]
- [x] Build with against API level 19 with build tools v19, up language level to 1.7.
- [x] Check GetGlue authentication with new WebView.
- [x] Set exact alarms for notifications (AlarmManager)

Sources:
http://developer.android.com/about/versions/android-4.4.html
http://tools.android.com/recent/androidstudio032released
